FROM python:3.9-slim

# הגדרת ספריית עבודה
WORKDIR /data-pipelines/dags

# העתקת קובץ requirements.txt לתוך המיכל
COPY requirements.txt .

# התקנת התלויות
RUN pip install --no-cache-dir -r requirements.txt

# העתקת קוד האפליקציה לתוך המיכל
COPY . .

# פקודת ברירת מחדל להפעלת האפליקציה
CMD ["python", "kafka_to_rds.py"]
