name: Build
 
on: 
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/build.yml' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image 
        run: |
          docker build -f data-pipelines/dags/Dockerfile-kafka_to_rds -t devops-data-platform-kafka:v1.0.0 ./data-pipelines/dags
          docker build -f data-pipelines/dags/Dockerfile-rds_to_redshift -t devops-data-platform-rds:v1.0.0 ./data-pipelines/dags  
          docker build -f data-pipelines/dags/Dockerfile-spark_batch_job -t devops-data-platform-spark:v1.0.0 ./data-pipelines/dags
