name: Build

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image 
        run: |
          docker build -t devops-data-platform:v1.0.0 ./app
            
